import Player from "../../Construtores/Mestre/Player";

export const TabelaPlayer: Player[] = [
  {
    img: "https://i.ibb.co/rfZHCpj/Debs.png",
    nivel: 2,
    nome: "Agatha",
    player: "Debs",
    classe: "Ladina",
    raca: "Humana",
    defesa: 0,
    atributos: {
      for: 0,
      des: 0,
      con: 0,
      int: 0,
      sab: 0,
      car: 0,
    },
    pvMax: 0,
    pvAtual: 0,
    pmMax: 0,
    pmAtual: 0,
    poderes: [
      {
        nome: "Lorem",
        descricao: "Ipsum",
        execucao: "Dolor",
      },
    ],
  },
  {
    img: "https://i.ibb.co/C9fwJc9/Bulan.png",
    nivel: 2,
    nome: "Per",
    player: "Bulan",
    classe: "Ladina",
    raca: "Sulfure",
    defesa: 0,
    atributos: {
      for: 0,
      des: 0,
      con: 0,
      int: 0,
      sab: 0,
      car: 0,
    },
    pvMax: 0,
    pvAtual: 0,
    pmMax: 0,
    pmAtual: 0,
    poderes: [
      {
        nome: "Lorem",
        descricao: "Ipsum",
        execucao: "Dolor",
      },
    ],
  },
  {
    img: "https://i.ibb.co/jfYVJtg/Diggo.png",
    nivel: 2,
    nome: "Tatum",
    player: "Diggo",
    classe: "Clérigo",
    raca: "Aggelus",
    defesa: 0,
    atributos: {
      for: 0,
      des: 0,
      con: 0,
      int: 0,
      sab: 0,
      car: 0,
    },
    pvMax: 0,
    pvAtual: 0,
    pmMax: 0,
    pmAtual: 0,
    poderes: [
      {
        nome: "Lorem",
        descricao: "Ipsum",
        execucao: "Dolor",
      },
    ],
  },
  {
    img: "https://i.ibb.co/jZHG2xx/Vic.png",
    nivel: 2,
    nome: "Akin",
    player: "Vic",
    classe: "Arcanista",
    raca: "Qareen",
    defesa: 0,
    atributos: {
      for: 0,
      des: 0,
      con: 0,
      int: 0,
      sab: 0,
      car: 0,
    },
    pvMax: 0,
    pvAtual: 0,
    pmMax: 0,
    pmAtual: 0,
    poderes: [
      {
        nome: "Lorem",
        descricao: "Ipsum",
        execucao: "Dolor",
      },
    ],
  },
  {
    img: "https://i.ibb.co/42Kdr9T/Moni.png",
    nivel: 2,
    nome: "Layla",
    player: "Moni",
    classe: "Arcanista",
    raca: "Elfa",
    defesa: 0,
    atributos: {
      for: 0,
      des: 0,
      con: 0,
      int: 0,
      sab: 0,
      car: 0,
    },
    pvMax: 0,
    pvAtual: 0,
    pmMax: 0,
    pmAtual: 0,
    poderes: [
      {
        nome: "Lorem",
        descricao: "Ipsum",
        execucao: "Dolor",
      },
    ],
  },
].sort((a, b) => a.player.localeCompare(b.player));
